services:
  web:
    build: ./portfolio_backend
    command: python manage.py runserver 0.0.0:8000
    volumes:
      - ./portfolio_backend/:/usr/src/portfolio_backend/
    ports:
      - "8000:8000" 
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: portfolio
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: