# Generated by Django 5.2.4 on 2025-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
    ]
