# Generated by Django 5.2.4 on 2025-09-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
